data = csvread("data/periodos.csv");
file = fopen("src/apendice/datos.tex", "wt");

for i = 1:50
    fprintf(file, ...
            "%i & $%3.2f$ & %i & $%3.2f$ & %i & $%3.2f$ & %i & $%3.2f$ \\\\\n", ...
            i, data(i), ...
            i + 50, data(i + 50), ...
            i + 100, data(i + 100), ...
            i + 150, data(i + 150));
end

fclose(file);
